// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qykontpmrpqkiymjhnnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5a29udHBtcnBxa2l5bWpobm5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjczOTgsImV4cCI6MjA2ODM0MzM5OH0.bs7fWkGFknqPLSGNLtAqQyjRpiFtA_o5ryj4nuoyE2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});